###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}


###
POST https://whatsapp-ten-lake.vercel.app/api/users/register
Content-Type: application/json

{
    "username": "admin1",
    "password": "1234"
}


###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}   