const { createCanvas, registerFont } = require('canvas');
const SalesOrder = require('../model/SalesOrder');
const License = require('../model/License');
const dayjs = require('dayjs');
const path = require('path');

exports.generateInvoiceImage = async (req, res) => {
    try {
        const orderID = req.params.id;
        const order = await SalesOrder.findOne({ OrderID: orderID });

        if (!order) {
            return res.status(404).send('Order not found');
        }

        // Fetch License info
        const license = await License.findOne({ _id: "STARINDIA" });
        const companyName = license?.CompanyName || "STAR INDIA";

        // Image Dimensions (approx A4 @ 72 DPI ish, scaled up for clarity)
        const width = 800;
        const height = 1200;
        const canvas = createCanvas(width, height);
        const ctx = canvas.getContext('2d');

        // Background
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, width, height);

        // Styling
        ctx.textBaseline = 'top';
        const margin = 50;
        let y = margin;

        // --- Header ---
        // Title
        ctx.fillStyle = '#3d3d3d';
        ctx.font = 'bold 36px Helvetica';
        ctx.fillText('Estimate', margin, y);
        y += 50;

        // Company
        ctx.fillStyle = '#000000';
        ctx.font = '16px Helvetica';
        ctx.fillText(companyName.toUpperCase(), margin, y);
        y += 30;

        // Line
        ctx.strokeStyle = '#aaaaaa';
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(margin, y);
        ctx.lineTo(width - margin, y);
        ctx.stroke();
        y += 30;

        // --- Details Section ---
        const detailsY = y;

        // Left: Bill To
        ctx.font = 'bold 14px Helvetica';
        ctx.fillText('Bill To:', margin, detailsY);

        ctx.font = '14px Helvetica';
        ctx.fillText(order.CustomerName || 'Guest', margin, detailsY + 20);
        ctx.fillText(order.CustomerPhone || '', margin, detailsY + 40);

        // Right: Estimate Info
        const rightColX = 500;
        ctx.font = 'bold 14px Helvetica';
        ctx.fillText(`Estimate #: ${order.OrderID}`, rightColX, detailsY);
        ctx.font = '14px Helvetica';
        ctx.fillText(`Date: ${dayjs(order.OrderDate).format('DD/MM/YYYY')}`, rightColX, detailsY + 20);

        y = detailsY + 80;

        // --- Table ---
        const tableTop = y;
        const colX = { item: margin, rate: 450, qty: 550, amount: 650 };

        // Header Row
        ctx.font = 'bold 14px Helvetica';
        ctx.fillText('Item', colX.item, tableTop);
        ctx.fillText('Rate', colX.rate, tableTop);
        ctx.fillText('Qty', colX.qty, tableTop);
        ctx.fillText('Amount', colX.amount, tableTop);

        // Header Line
        y += 20;
        ctx.beginPath();
        ctx.moveTo(margin, y);
        ctx.lineTo(width - margin, y);
        ctx.stroke();
        y += 10;

        // Items Loop
        ctx.font = '14px Helvetica';

        for (let i = 0; i < order.Items.length; i++) {
            const item = order.Items[i];

            // Item Name
            ctx.fillText(item.ItemName, colX.item, y);

            // Rate (Right Align somewhat manually or just standard)
            ctx.fillText(item.Rate.toString(), colX.rate, y);

            // Qty
            ctx.fillText(item.Qty.toString(), colX.qty, y);

            // Total
            ctx.fillText(item.Total.toFixed(2), colX.amount, y);

            // Row Line
            y += 20;
            ctx.strokeStyle = '#ebebeb';
            ctx.beginPath();
            ctx.moveTo(margin, y);
            ctx.lineTo(width - margin, y);
            ctx.stroke();
            y += 10;
        }

        // --- Totals ---
        y += 20;
        const totalX = 500;

        if (order.ExtraDiscount && order.ExtraDiscount > 0) {
            ctx.font = '14px Helvetica';
            ctx.fillText(`Extra Discount: ${order.ExtraDiscount}`, totalX, y);
            y += 20;
        }

        ctx.font = 'bold 16px Helvetica';
        ctx.fillText('Total:', totalX, y);
        ctx.fillText(`₹ ${order.TotalAmount.toFixed(2)}`, totalX + 60, y);

        // --- Footer ---
        const footerY = height - 100;
        ctx.font = 'bold 12px Helvetica';
        ctx.fillText('Terms & Conditions', margin, footerY);

        ctx.font = '12px Helvetica';
        ctx.fillText('Payment is due within 15 days.', margin, footerY + 20);

        ctx.fillStyle = '#888888';
        ctx.font = '10px Helvetica';
        const brandText = 'Generated by LocalStore';
        const brandWidth = ctx.measureText(brandText).width;
        ctx.fillText(brandText, (width - brandWidth) / 2, height - 30);

        // Output as PNG Stream
        res.setHeader('Content-Type', 'image/png');
        // Optional: disposition attachment if we want to force download, but inline is better for browser preview
        // res.setHeader('Content-Disposition', `inline; filename="Invoice_${order.OrderID}.png"`);

        const stream = canvas.createPNGStream();
        stream.pipe(res);

    } catch (error) {
        console.error("Error generating invoice image:", error);
        res.status(500).send('Error generating invoice image');
    }
};
